#!/bin/bash

#SBATCH --job-name=megahit_ruben
#SBATCH --output=megahit_ruben.%j.out
#SBATCH --error=megahit_ruben.%j.err
#SBATCH --cpus-per-task=4           # Pugem a 8 per anar més ràpid
#SBATCH --mem=32G                   # L'assemblatge necessita força RAM
#SBATCH --time=24:00:00             

# Evitem problemes de llenguatge
export LC_ALL=C
export LANG=C

module load miniconda3
source ~/.bashrc
conda activate shotgun1  # Assegura't que megahit està instal·lat aquí

# --- CONFIGURACIÓ DE RUTES ---
INPUT_DIR="/home/41701728z/indexos"      # On hem guardat els fastq_nonhuman
OUTPUT_ROOT="/home/41701728z/assemblies" # On aniran els resultats de l'assemblatge

mkdir -p "$OUTPUT_ROOT"

# Bucle per processar cada parella de fitxers nonhuman
for R1 in "$INPUT_DIR"/*_nonhuman_R1.fastq.gz; do
    # Obtenim el nom de la mostra (ex: SRR13300632)
    BASE=$(basename "${R1}" _nonhuman_R1.fastq.gz)
    R2="$INPUT_DIR"/"$BASE"_nonhuman_R2.fastq.gz
    
    echo "--------------------------------------------------------"
    echo "INICIANT ASSEMBLATGE MEGAHIT PER A LA MOSTRA: $BASE"
    echo "--------------------------------------------------------"

    # Execució de MEGAHIT
    # --presets meta-large: Ideal per metagenomes complexos
    # --out-prefix: Nom que portaran els fitxers de sortida
    megahit -1 "$R1" \
            -2 "$R2" \
            -t 4 \
            --presets meta-large \
            --out-dir "$OUTPUT_ROOT/megahit_$BASE" \
            --out-prefix "$BASE"

    echo "Assemblatge de $BASE finalitzat."
done

echo "Tots els assemblatges s'han completat correctament."
